version: '3.2'
services:

  kafka-producer:
    build: /mnt/c/Dev Projects/Monitoring & Security/Monitoring Kafka/KafkaProducer/
    depends_on:
     - kafka
    command: tail -F anything

  kafka-consumer:
    build: /mnt/c/Dev Projects/Monitoring & Security/Monitoring Kafka/KafkaConsumer/
    depends_on:
     - kafka
    command: tail -F anything
    
  prometheus:
   image: prom/prometheus
   ports:
     - "9090:9090"
   volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
   image: grafana/grafana
   ports:
     - "3000:3000"
   volumes:
     - ./grafana:/var/lib/grafana

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092


  zookeeper:
   image: wurstmeister/zookeeper
   ports:
     - "2181:2181"

  kafka:
    build: .
    links:
        - zookeeper
    ports:
        - "9092:9092"
    environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        EXTRA_ARGS: -javaagent:/usr/app/jmx_prometheus_javaagent.jar=7071:/usr/app/prom-jmx-agent-config.yml
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock